### ISSUE TITLE
Autodetect or allow specifying default edge type on write

### ISSUE THREAD

**Issue by joshhansen** [graphology/graphology-gexf#27]
`gexf.write` seems to default to a directed edge type, even when my graph contains only undirected edges. This makes Gephi reject the graph when I try to load it.

Can we either autodetect the default edge type, or allow it to be specified on write?

**Comment by Yomguithereal** [comment]
Hello @joshhansen, is your graph (as represented by graphology) undirected or mixed? Also can you provide a minimal graph example so I can fix the issue please?

**Comment by Yomguithereal** [comment]
Ok I think your issue happens with mixed graphs only. I think I will be able to fix this soon.

**Comment by Yomguithereal** [comment]
I can't seem to be able to reproduce your issue @joshhansen. In any case I have slightly improved the writer's type inference for mixed graphs containing only directed or undirected edges. This is released as v0.7.5. Tell me if this fixes your issue.
